import 'package:absa_cib_ecg_dashboard/models/revenue_model.dart';
import 'package:absa_cib_ecg_dashboard/models/emissions_model.dart';

import '/models/company_info_model.dart';
import 'package:flutter/services.dart' show ByteData, rootBundle;
import 'dart:core';
import 'package:path/path.dart' as p;

import 'package:excel/excel.dart';

ByteData? data = rootBundle.load("assets/CompanyData.xlsx") as ByteData?;
var bytes = data!.buffer.asUint8List(data!.offsetInBytes, data?.lengthInBytes);
var excel = Excel.decodeBytes(bytes);

var table = excel.tables.keys.first;

List<CompInfo> companies = [
  CompInfo(
      name: excel.tables[table]!.rows[0][0],
      sector: excel.tables[table]!.rows[0][1],
      scope1_2021: excel.tables[table]!.rows[0][2],
      scope2_2021: excel.tables[table]!.rows[0][3],
      rev2021: excel.tables[table]!.rows[0][4],
      scope1_2020: excel.tables[table]!.rows[0][5],
      scope2_2020: excel.tables[table]!.rows[0][6],
      rev2020: excel.tables[table]!.rows[0][7],
      iconSrc: excel.tables[table]!.rows[0][8]),
  CompInfo(
      name: excel.tables[table]!.rows[1][0],
      sector: excel.tables[table]!.rows[1][1],
      scope1_2021: excel.tables[table]!.rows[1][2],
      scope2_2021: excel.tables[table]!.rows[1][3],
      rev2021: excel.tables[table]!.rows[1][4],
      scope1_2020: excel.tables[table]!.rows[1][5],
      scope2_2020: excel.tables[table]!.rows[1][6],
      rev2020: excel.tables[table]!.rows[1][7],
      iconSrc: excel.tables[table]!.rows[1][8]),
  CompInfo(
      name: excel.tables[table]!.rows[2][0],
      sector: excel.tables[table]!.rows[2][1],
      scope1_2021: excel.tables[table]!.rows[2][2],
      scope2_2021: excel.tables[table]!.rows[2][3],
      rev2021: excel.tables[table]!.rows[2][4],
      scope1_2020: excel.tables[table]!.rows[2][5],
      scope2_2020: excel.tables[table]!.rows[2][6],
      rev2020: excel.tables[table]!.rows[2][7],
      iconSrc: excel.tables[table]!.rows[2][8]),
  CompInfo(
      name: excel.tables[table]!.rows[3][0],
      sector: excel.tables[table]!.rows[3][1],
      scope1_2021: excel.tables[table]!.rows[3][2],
      scope2_2021: excel.tables[table]!.rows[3][3],
      rev2021: excel.tables[table]!.rows[3][4],
      scope1_2020: excel.tables[table]!.rows[3][5],
      scope2_2020: excel.tables[table]!.rows[3][6],
      rev2020: excel.tables[table]!.rows[3][7],
      iconSrc: excel.tables[table]!.rows[3][8]),
  CompInfo(
      name: excel.tables[table]!.rows[4][0],
      sector: excel.tables[table]!.rows[4][1],
      scope1_2021: excel.tables[table]!.rows[4][2],
      scope2_2021: excel.tables[table]!.rows[4][3],
      rev2021: excel.tables[table]!.rows[4][4],
      scope1_2020: excel.tables[table]!.rows[4][5],
      scope2_2020: excel.tables[table]!.rows[4][6],
      rev2020: excel.tables[table]!.rows[4][7],
      iconSrc: excel.tables[table]!.rows[4][8]),
  CompInfo(
      name: excel.tables[table]!.rows[5][0],
      sector: excel.tables[table]!.rows[5][1],
      scope1_2021: excel.tables[table]!.rows[5][2],
      scope2_2021: excel.tables[table]!.rows[5][3],
      rev2021: excel.tables[table]!.rows[5][4],
      scope1_2020: excel.tables[table]!.rows[5][5],
      scope2_2020: excel.tables[table]!.rows[5][6],
      rev2020: excel.tables[table]!.rows[5][7],
      iconSrc: excel.tables[table]!.rows[5][8]),
  CompInfo(
      name: excel.tables[table]!.rows[6][0],
      sector: excel.tables[table]!.rows[6][1],
      scope1_2021: excel.tables[table]!.rows[6][2],
      scope2_2021: excel.tables[table]!.rows[6][3],
      rev2021: excel.tables[table]!.rows[6][4],
      scope1_2020: excel.tables[table]!.rows[6][5],
      scope2_2020: excel.tables[table]!.rows[6][6],
      rev2020: excel.tables[table]!.rows[6][7],
      iconSrc: excel.tables[table]!.rows[6][8]),
  CompInfo(
      name: excel.tables[table]!.rows[7][0],
      sector: excel.tables[table]!.rows[7][1],
      scope1_2021: excel.tables[table]!.rows[7][2],
      scope2_2021: excel.tables[table]!.rows[7][3],
      rev2021: excel.tables[table]!.rows[7][4],
      scope1_2020: excel.tables[table]!.rows[7][5],
      scope2_2020: excel.tables[table]!.rows[7][6],
      rev2020: excel.tables[table]!.rows[7][7],
      iconSrc: excel.tables[table]!.rows[7][8]),
  CompInfo(
      name: excel.tables[table]!.rows[8][0],
      sector: excel.tables[table]!.rows[8][1],
      scope1_2021: excel.tables[table]!.rows[8][2],
      scope2_2021: excel.tables[table]!.rows[8][3],
      rev2021: excel.tables[table]!.rows[8][4],
      scope1_2020: excel.tables[table]!.rows[8][5],
      scope2_2020: excel.tables[table]!.rows[8][6],
      rev2020: excel.tables[table]!.rows[8][7],
      iconSrc: excel.tables[table]!.rows[8][8]),
  CompInfo(
      name: excel.tables[table]!.rows[9][0],
      sector: excel.tables[table]!.rows[9][1],
      scope1_2021: excel.tables[table]!.rows[9][2],
      scope2_2021: excel.tables[table]!.rows[9][3],
      rev2021: excel.tables[table]!.rows[9][4],
      scope1_2020: excel.tables[table]!.rows[9][5],
      scope2_2020: excel.tables[table]!.rows[9][6],
      rev2020: excel.tables[table]!.rows[9][7],
      iconSrc: excel.tables[table]!.rows[9][8]),
  CompInfo(
      name: excel.tables[table]!.rows[10][0],
      sector: excel.tables[table]!.rows[10][1],
      scope1_2021: excel.tables[table]!.rows[10][2],
      scope2_2021: excel.tables[table]!.rows[10][3],
      rev2021: excel.tables[table]!.rows[10][4],
      scope1_2020: excel.tables[table]!.rows[10][5],
      scope2_2020: excel.tables[table]!.rows[10][6],
      rev2020: excel.tables[table]!.rows[10][7],
      iconSrc: excel.tables[table]!.rows[10][8]),
  CompInfo(
      name: excel.tables[table]!.rows[11][0],
      sector: excel.tables[table]!.rows[11][1],
      scope1_2021: excel.tables[table]!.rows[11][2],
      scope2_2021: excel.tables[table]!.rows[11][3],
      rev2021: excel.tables[table]!.rows[11][4],
      scope1_2020: excel.tables[table]!.rows[11][5],
      scope2_2020: excel.tables[table]!.rows[11][6],
      rev2020: excel.tables[table]!.rows[11][7],
      iconSrc: excel.tables[table]!.rows[11][8]),
  CompInfo(
      name: excel.tables[table]!.rows[12][0],
      sector: excel.tables[table]!.rows[12][1],
      scope1_2021: excel.tables[table]!.rows[12][2],
      scope2_2021: excel.tables[table]!.rows[12][3],
      rev2021: excel.tables[table]!.rows[12][4],
      scope1_2020: excel.tables[table]!.rows[12][5],
      scope2_2020: excel.tables[table]!.rows[12][6],
      rev2020: excel.tables[table]!.rows[12][7],
      iconSrc: excel.tables[table]!.rows[12][8]),
  CompInfo(
      name: excel.tables[table]!.rows[13][0],
      sector: excel.tables[table]!.rows[13][1],
      scope1_2021: excel.tables[table]!.rows[13][2],
      scope2_2021: excel.tables[table]!.rows[13][3],
      rev2021: excel.tables[table]!.rows[13][4],
      scope1_2020: excel.tables[table]!.rows[13][5],
      scope2_2020: excel.tables[table]!.rows[13][6],
      rev2020: excel.tables[table]!.rows[13][7],
      iconSrc: excel.tables[table]!.rows[13][8]),
  CompInfo(
      name: excel.tables[table]!.rows[14][0],
      sector: excel.tables[table]!.rows[14][1],
      scope1_2021: excel.tables[table]!.rows[14][2],
      scope2_2021: excel.tables[table]!.rows[14][3],
      rev2021: excel.tables[table]!.rows[14][4],
      scope1_2020: excel.tables[table]!.rows[14][5],
      scope2_2020: excel.tables[table]!.rows[14][6],
      rev2020: excel.tables[table]!.rows[14][7],
      iconSrc: excel.tables[table]!.rows[14][8]),
  CompInfo(
      name: excel.tables[table]!.rows[15][0],
      sector: excel.tables[table]!.rows[15][1],
      scope1_2021: excel.tables[table]!.rows[15][2],
      scope2_2021: excel.tables[table]!.rows[15][3],
      rev2021: excel.tables[table]!.rows[15][4],
      scope1_2020: excel.tables[table]!.rows[15][5],
      scope2_2020: excel.tables[table]!.rows[15][6],
      rev2020: excel.tables[table]!.rows[15][7],
      iconSrc: excel.tables[table]!.rows[15][8]),
  CompInfo(
      name: excel.tables[table]!.rows[16][0],
      sector: excel.tables[table]!.rows[16][1],
      scope1_2021: excel.tables[table]!.rows[16][2],
      scope2_2021: excel.tables[table]!.rows[16][3],
      rev2021: excel.tables[table]!.rows[16][4],
      scope1_2020: excel.tables[table]!.rows[16][5],
      scope2_2020: excel.tables[table]!.rows[16][6],
      rev2020: excel.tables[table]!.rows[16][7],
      iconSrc: excel.tables[table]!.rows[16][8]),
  CompInfo(
      name: excel.tables[table]!.rows[17][0],
      sector: excel.tables[table]!.rows[17][1],
      scope1_2021: excel.tables[table]!.rows[17][2],
      scope2_2021: excel.tables[table]!.rows[17][3],
      rev2021: excel.tables[table]!.rows[17][4],
      scope1_2020: excel.tables[table]!.rows[17][5],
      scope2_2020: excel.tables[table]!.rows[17][6],
      rev2020: excel.tables[table]!.rows[17][7],
      iconSrc: excel.tables[table]!.rows[17][8]),
];

List<EmissionsInfo> emissions = [
  companies[0].getEmissions(),
  companies[1].getEmissions(),
  companies[2].getEmissions(),
  companies[3].getEmissions(),
  companies[4].getEmissions(),
  companies[5].getEmissions(),
  companies[6].getEmissions(),
  companies[7].getEmissions(),
  companies[8].getEmissions(),
  companies[9].getEmissions(),
  companies[10].getEmissions(),
  companies[11].getEmissions(),
  companies[12].getEmissions(),
  companies[13].getEmissions(),
  companies[14].getEmissions(),
  companies[15].getEmissions(),
  companies[16].getEmissions(),
  companies[17].getEmissions()
];

List<RevenueInfo> revenue = [
  companies[0].getRev(),
  companies[1].getRev(),
  companies[2].getRev(),
  companies[3].getRev(),
  companies[4].getRev(),
  companies[5].getRev(),
  companies[6].getRev(),
  companies[7].getRev(),
  companies[8].getRev(),
  companies[9].getRev(),
  companies[10].getRev(),
  companies[11].getRev(),
  companies[12].getRev(),
  companies[13].getRev(),
  companies[14].getRev(),
  companies[15].getRev(),
  companies[16].getRev(),
  companies[17].getRev()
];
